app:
  port: 2000
  doc_folder: /var/readthedocs
  tls:
    cert_file:
    key_file:

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  db_name: postgres
  ssl_mode: disable
  migrate: true
